name: Run shell script.

on:
  workflow_dispatch:

jobs:
  Run_Shell_Script:
    runs-on: ubuntu-latest
    steps:
      - name: checout action
        uses: actions/checkout@v4

      - name: Run shell Script
        run: |
          ls -lart
          cd password generator
          chmod +x password_generator.sh
          ./password_generator.sh
